<#
.SYNOPSIS
  Keel installer for Windows.

.DESCRIPTION
  Installs Keel into a directory, configures it, builds it, and optionally
  registers a scheduled task so it starts on boot.

  Re-running is safe: an existing install is updated and an existing .env is
  preserved, except for the exact blocked first-account template generated by
  the Keel 1.2.1 installers.

.EXAMPLE
  irm https://raw.githubusercontent.com/AES256Afro/Keel/main/install.ps1 | iex

.EXAMPLE
  .\install.ps1 -Dir C:\Keel -Port 3000 -Owner you@example.com -Service
#>
[CmdletBinding()]
param(
  [string]$Dir     = "$env:LOCALAPPDATA\Keel",
  [int]   $Port    = 3000,
  [string]$Owner   = "",
  [string]$Branch  = "main",
  [string]$Repo    = "https://github.com/AES256Afro/Keel",
  [switch]$Service,
  [switch]$Yes
)

$ErrorActionPreference = "Stop"
$createdEnv = $false
$recoveredLegacyAccess = $false

function Say  ($m) { Write-Host "==> $m" -ForegroundColor White }
function Ok   ($m) { Write-Host "  [ok] $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  [!]  $m" -ForegroundColor Yellow }
function Die  ($m) { Write-Host "  [x]  $m" -ForegroundColor Red; exit 1 }

function Confirm-Step($message) {
  if ($Yes) { return $true }
  $reply = Read-Host "  $message [y/N]"
  return $reply -match '^[yY]'
}

# Data, managed-credential keys, and backups must not inherit access from the
# directory where Keel was cloned. Use well-known SIDs so this works on
# localized Windows installations, then verify the effective DACL before the
# installer is allowed to continue.
function Set-KeelRestrictedAcl {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [switch]$Recurse
  )

  try {
    $currentUserSid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User
    if (-not $currentUserSid) {
      throw "Windows did not return a SID for the current user"
    }

    $allowedSids = @(
      $currentUserSid,
      [System.Security.Principal.SecurityIdentifier]::new("S-1-5-18"),
      [System.Security.Principal.SecurityIdentifier]::new("S-1-5-32-544")
    ) | Sort-Object -Property Value -Unique

    $root = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
    if (($root.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
      throw "'$($root.FullName)' is a reparse point; refusing to change an external target"
    }

    $pending = [System.Collections.Generic.Queue[System.IO.FileSystemInfo]]::new()
    $pending.Enqueue($root)

    while ($pending.Count -gt 0) {
      $item = $pending.Dequeue()
      $isDirectory = $item -is [System.IO.DirectoryInfo]
      $inheritance = [System.Security.AccessControl.InheritanceFlags]::None
      if ($isDirectory) {
        $inheritance = (
          [System.Security.AccessControl.InheritanceFlags]::ContainerInherit -bor
          [System.Security.AccessControl.InheritanceFlags]::ObjectInherit
        )
      }

      $acl = Get-Acl -LiteralPath $item.FullName -ErrorAction Stop
      $acl.SetAccessRuleProtection($true, $false)
      foreach ($oldRule in @($acl.Access)) {
        $acl.PurgeAccessRules($oldRule.IdentityReference)
      }
      $acl.SetOwner($currentUserSid)

      foreach ($sid in $allowedSids) {
        $rule = [System.Security.AccessControl.FileSystemAccessRule]::new(
          $sid,
          [System.Security.AccessControl.FileSystemRights]::FullControl,
          $inheritance,
          [System.Security.AccessControl.PropagationFlags]::None,
          [System.Security.AccessControl.AccessControlType]::Allow
        )
        [void]$acl.AddAccessRule($rule)
      }
      Set-Acl -LiteralPath $item.FullName -AclObject $acl -ErrorAction Stop

      $verified = Get-Acl -LiteralPath $item.FullName -ErrorAction Stop
      if (-not $verified.AreAccessRulesProtected) {
        throw "'$($item.FullName)' still inherits access rules"
      }

      $ownerSid = $verified.GetOwner(
        [System.Security.Principal.SecurityIdentifier]
      ).Value
      if ($ownerSid -ne $currentUserSid.Value) {
        throw "'$($item.FullName)' is not owned by the current user"
      }

      $verifiedRules = @($verified.Access)
      if ($verifiedRules.Count -ne $allowedSids.Count) {
        throw "'$($item.FullName)' has an unexpected number of access rules"
      }
      $seenSids = @{}
      foreach ($verifiedRule in $verifiedRules) {
        $ruleSid = $verifiedRule.IdentityReference.Translate(
          [System.Security.Principal.SecurityIdentifier]
        ).Value
        if ($ruleSid -notin $allowedSids.Value) {
          throw "'$($item.FullName)' grants access to unexpected identity $ruleSid"
        }
        if ($verifiedRule.IsInherited -or
            $verifiedRule.AccessControlType -ne [System.Security.AccessControl.AccessControlType]::Allow -or
            ($verifiedRule.FileSystemRights -band [System.Security.AccessControl.FileSystemRights]::FullControl) -ne
              [System.Security.AccessControl.FileSystemRights]::FullControl -or
            $verifiedRule.InheritanceFlags -ne $inheritance -or
            $verifiedRule.PropagationFlags -ne [System.Security.AccessControl.PropagationFlags]::None) {
          throw "'$($item.FullName)' has an unexpected access rule for $ruleSid"
        }
        $seenSids[$ruleSid] = $true
      }
      foreach ($sid in $allowedSids) {
        if (-not $seenSids.ContainsKey($sid.Value)) {
          throw "'$($item.FullName)' is missing the required access rule for $($sid.Value)"
        }
      }

      if ($Recurse -and $isDirectory) {
        foreach ($child in Get-ChildItem -LiteralPath $item.FullName -Force -ErrorAction Stop) {
          if (($child.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "'$($child.FullName)' is a reparse point; refusing to change an external target"
          }
          $pending.Enqueue($child)
        }
      }
    }
  } catch {
    throw "Could not secure '$Path': $($_.Exception.Message)"
  }
}

Say "Keel installer"
Write-Host "  target: $Dir (port $Port)" -ForegroundColor DarkGray
Write-Host ""

# ------------------------------------------------------------------- node ---
Say "Checking Node.js"
$nodeOk = $false
if (Get-Command node -ErrorAction SilentlyContinue) {
  $major = [int](((node --version) -replace '^v','') -split '\.')[0]
  if ($major -ge 20) { $nodeOk = $true; Ok "Node.js $(node --version)" }
  else { Warn "Node.js $(node --version) is too old - Keel needs 20 or newer." }
} else {
  Warn "Node.js is not installed."
}

if (-not $nodeOk) {
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    if (Confirm-Step "Install Node.js LTS with winget?") {
      winget install --id OpenJS.NodeJS.LTS --accept-source-agreements --accept-package-agreements
      # winget updates PATH for new shells only.
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                  [System.Environment]::GetEnvironmentVariable("Path","User")
    } else { Die "Node.js 20 or newer is required." }
  } else {
    Die "Install Node.js 20+ from https://nodejs.org and re-run."
  }
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    if (Confirm-Step "Install Git with winget?") {
      winget install --id Git.Git --accept-source-agreements --accept-package-agreements
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                  [System.Environment]::GetEnvironmentVariable("Path","User")
    } else { Die "git is required." }
  } else { Die "Install Git from https://git-scm.com and re-run." }
}
Ok "git present"

# Kept only so older unattended install commands continue to run. The signed-in
# one-use claim flow selects the account; this value is never written to .env.
$Owner = $Owner.Trim().ToLowerInvariant()
if ($Owner -and ($Owner.Length -gt 254 -or $Owner -notmatch '^[^\s@"\\]+@[^\s@"\\]+$')) {
  Die "'$Owner' is not a valid email address."
}
if ($Owner) {
  Warn "-Owner is accepted for older scripts but no longer selects the server owner."
}

# ------------------------------------------------------------------ fetch ---
Say "Fetching Keel"
if (Test-Path (Join-Path $Dir ".git")) {
  git -C $Dir fetch --depth 1 origin $Branch
  git -C $Dir checkout -q $Branch 2>$null
  git -C $Dir reset --hard "origin/$Branch"
  Ok "updated $Dir"
} else {
  if ((Test-Path $Dir) -and (Get-ChildItem $Dir -Force | Measure-Object).Count -gt 0) {
    Die "$Dir exists and is not empty."
  }
  git clone --depth 1 --branch $Branch $Repo $Dir
  Ok "cloned into $Dir"
}
Set-Location $Dir

# -------------------------------------------------------------------- env ---
Say "Configuring"
$dataDir   = Join-Path $Dir "data"
$backupDir = Join-Path $Dir "backups"
New-Item -ItemType Directory -Force -Path $dataDir, $backupDir | Out-Null
try {
  # This also repairs every existing database, managed-secret key, and backup
  # before Prisma or the running application can create or open sensitive data.
  Set-KeelRestrictedAcl -Path $dataDir -Recurse
  Set-KeelRestrictedAcl -Path $backupDir -Recurse
  Ok "data and backup permissions restricted"
} catch {
  Die "Keel cannot safely use its data directories. Refusing to continue. $($_.Exception.Message)"
}

$envFile = Join-Path $Dir ".env"
if (Test-Path $envFile) {
  Ok ".env already exists - preserving existing settings"
} else {
  $passphrase = node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))"
  # Prisma wants forward slashes in a file: URL, even on Windows.
  $dbPath = ($dataDir -replace '\\','/') + "/keel.db"
  $stamp  = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  @"
# Generated by install.ps1 on $stamp

DATABASE_URL="file:$dbPath"
PORT=$Port

# Claiming starts in the signed-in app and separately confirms control of this machine.
KEEL_CLAIM_REQUIRED=1

# Registration stays open on this local install. After claiming the server, its
# owner can change registration policy in Settings > Registration and sign-in.

# Passphrase for encrypted backups. Keep a copy somewhere safe - without it an
# encrypted backup cannot be restored.
KEEL_BACKUP_PASSPHRASE="$passphrase"

KEEL_BACKUP_DIR="$($backupDir -replace '\\','/')"
"@ | Set-Content -Path $envFile -Encoding UTF8

  # Give Prisma an empty SQLite file to initialize. Existing databases are
  # never changed here.
  if (-not (Test-Path $dbPath)) {
    New-Item -ItemType File -Path $dbPath | Out-Null
  }

  # Restrict the file to the current user - it holds the backup passphrase.
  $acl = Get-Acl $envFile
  $acl.SetAccessRuleProtection($true, $false)
  $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "$env:USERDOMAIN\$env:USERNAME", "FullControl", "Allow")
  $acl.SetAccessRule($rule)
  Set-Acl $envFile $acl

  $createdEnv = $true
  Ok "wrote .env"
  Warn "back up KEEL_BACKUP_PASSPHRASE from .env - encrypted backups need it"
}

# ---------------------------------------------------------------- install ---
$stoppedManagedTask = $false
$stoppedManagedTaskXml = $null
$installSucceeded = $false
try {
  $existingTask = Get-ScheduledTask -TaskName "Keel" -ErrorAction SilentlyContinue
  if ($existingTask -and $existingTask.State -eq "Running") {
    $taskActions = @($existingTask.Actions)
    $taskExecutable = if ($taskActions.Count -eq 1) {
      [System.IO.Path]::GetFileName($taskActions[0].Execute)
    } else { "" }
    $taskLooksLikeKeel = (
      $taskExecutable -ieq "cmd.exe" -and
      $taskActions[0].Arguments -match '(?i)\bnpm(?:\.cmd)?[^\r\n]*\bstart\b'
    )
    if ($taskActions.Count -eq 1 -and $taskLooksLikeKeel -and $taskActions[0].WorkingDirectory) {
      $targetDir = [System.IO.Path]::GetFullPath($Dir).TrimEnd('\')
      $taskDir = [System.IO.Path]::GetFullPath($taskActions[0].WorkingDirectory).TrimEnd('\')
      if ([string]::Equals($targetDir, $taskDir, [System.StringComparison]::OrdinalIgnoreCase)) {
        $stoppedManagedTaskXml = Export-ScheduledTask -TaskName "Keel" -ErrorAction Stop
        if (-not $stoppedManagedTaskXml) {
          throw "Could not preserve the verified Keel scheduled task before updating."
        }
        Stop-ScheduledTask -TaskName "Keel"
        $stoppedManagedTask = $true
        for ($attempt = 0; $attempt -lt 100; $attempt++) {
          $taskState = (Get-ScheduledTask -TaskName "Keel" -ErrorAction Stop).State
          if ($taskState -ne "Running") { break }
          Start-Sleep -Milliseconds 100
        }
        if ((Get-ScheduledTask -TaskName "Keel" -ErrorAction Stop).State -eq "Running") {
          throw "The verified Keel scheduled task did not stop before the update."
        }
        Ok "temporarily stopped the verified Keel scheduled task"
      }
    }
  }

  Say "Installing dependencies"
  npm ci --no-audit --no-fund
  if ($LASTEXITCODE -ne 0) { throw "npm ci failed with exit code $LASTEXITCODE" }
  npx prisma generate | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "Prisma generation failed with exit code $LASTEXITCODE" }
  Ok "dependencies installed"

  # Keep the original Windows ACL across the helper's atomic replacement. The
  # helper itself preserves the byte encoding, non-access settings, and file mode.
  if (-not $createdEnv) {
    $existingEnvAcl = Get-Acl $envFile
    $legacyRecoveryStatus = ((& node scripts/recover-v121-installer-env.mjs $envFile) | Out-String).Trim()
    if ($LASTEXITCODE -ne 0) { throw "Legacy access inspection failed with exit code $LASTEXITCODE" }
    if ($legacyRecoveryStatus -eq "repaired") {
      Set-Acl -Path $envFile -AclObject $existingEnvAcl
      $recoveredLegacyAccess = $true
      Warn "repaired the blocked Keel 1.2.1 first-account setting"
    }
  }

  Say "Creating the database"
  npm run db:deploy
  if ($LASTEXITCODE -ne 0) {
    throw "Database migration failed. Stop any manually started Keel process and re-run the installer."
  }
  Ok "database ready"

  Say "Building"
  npm run build
  if ($LASTEXITCODE -ne 0) { throw "Keel build failed with exit code $LASTEXITCODE" }
  Ok "built"
  $installSucceeded = $true
} finally {
  # A successful -Service update replaces and starts the verified task below.
  # Every other path restores the exact task that this run stopped.
  if ($stoppedManagedTask -and (-not $installSucceeded -or -not $Service)) {
    try {
      Start-ScheduledTask -TaskName "Keel"
      Ok "restarted the existing Keel scheduled task"
      $stoppedManagedTask = $false
    } catch {
      $restartError = $_.Exception.Message
      $restoredPreservedTask = $false
      if ($stoppedManagedTaskXml) {
        try {
          Register-ScheduledTask -TaskName "Keel" -Xml $stoppedManagedTaskXml -Force | Out-Null
          Start-ScheduledTask -TaskName "Keel"
          $stoppedManagedTask = $false
          $restoredPreservedTask = $true
          Warn "restored the preserved Keel scheduled task definition"
        } catch {
          $restartError = "$restartError; preserved task restoration failed: $($_.Exception.Message)"
        }
      }
      if (-not $restoredPreservedTask -and $installSucceeded) {
        throw "The update succeeded, but the existing Keel scheduled task could not be restarted: $restartError"
      }
      if (-not $restoredPreservedTask) {
        Warn "the update failed and the existing Keel scheduled task could not be restarted automatically"
      }
    }
  }
}

# ---------------------------------------------------------------- service ---
if ($Service) {
  try {
    Say "Registering the startup task"
    $taskName = "Keel"
    $npmCmd   = (Get-Command npm -ErrorAction Stop).Source
    # cmd.exe wrapper: npm is a shim, and Task Scheduler will not run it directly.
    $action   = New-ScheduledTaskAction -Execute "cmd.exe" `
                  -Argument "/c `"$npmCmd`" start" -WorkingDirectory $Dir
    $trigger  = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
                  -DontStopIfGoingOnBatteries -StartWhenAvailable `
                  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

    # -Force updates the stopped definition in place. Unlike unregistering it
    # first, a registration failure leaves the prior task available to restore.
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
      -Settings $settings -Description "Keel workspace server" -Force | Out-Null
    Start-ScheduledTask -TaskName $taskName
    $stoppedManagedTask = $false
    Ok "scheduled task '$taskName' registered and started"
  } catch {
    $replacementError = $_
    if ($stoppedManagedTask) {
      try {
        if ($stoppedManagedTaskXml) {
          Register-ScheduledTask -TaskName "Keel" -Xml $stoppedManagedTaskXml -Force | Out-Null
        }
        Start-ScheduledTask -TaskName "Keel"
        $stoppedManagedTask = $false
        Warn "service replacement failed; restarted the prior Keel scheduled task"
      } catch {
        Warn "service replacement failed and the prior Keel scheduled task could not be restarted"
      }
    }
    throw $replacementError
  }
}

# A running process keeps the old environment until it restarts. If this is a
# recovery-only rerun, restart an existing managed task automatically.
$recoveryRestarted = $false
if ($recoveredLegacyAccess -and -not $Service) {
  $existingTask = Get-ScheduledTask -TaskName "Keel" -ErrorAction SilentlyContinue
  if ($existingTask) {
    try {
      Stop-ScheduledTask -TaskName "Keel" -ErrorAction SilentlyContinue
      Start-ScheduledTask -TaskName "Keel"
      $recoveryRestarted = $true
      Ok "restarted the existing scheduled task"
    } catch {
      Warn "Could not restart the existing scheduled task automatically."
    }
  }
}

Write-Host ""
Say "Done."
if ($Service) {
  Write-Host "  Keel is running at http://localhost:$Port" -ForegroundColor Green
} else {
  $safeDir = "'" + $Dir.Replace("'", "''") + "'"
  Write-Host "  Start it with:  Set-Location -LiteralPath $safeDir; npm start"
  Write-Host "  Then open:      http://localhost:$Port"
  Write-Host "  Re-run with -Service to start it automatically at logon." -ForegroundColor DarkGray
}
if ($createdEnv) {
  Write-Host "  1. Register an account in Keel." -ForegroundColor Green
  Write-Host "  2. In Welcome or Settings, open Claim this server."
  Write-Host "  3. Generate and copy the exact one-use claim command shown there."
  Write-Host "  4. Run it in PowerShell and complete fresh OS administrator authorization."
  Write-Host "  The browser never asks for or receives your operating-system password." -ForegroundColor DarkGray
  Write-Host "  Registration remains open until the server owner changes it in Settings > Registration and sign-in." -ForegroundColor DarkGray
} else {
  if ($recoveredLegacyAccess) {
    Write-Host "  Existing access settings were repaired."
    Write-Host "  The old hard signup stop was removed; the existing owner allowlist remains." -ForegroundColor DarkGray
    if (-not $recoveryRestarted -and -not $Service) {
      Write-Host "  Stop any running Keel process, then start it again so the repair takes effect." -ForegroundColor Yellow
    }
    Write-Host "  Register with the KEEL_ALLOWED_EMAILS address retained in .env." -ForegroundColor DarkGray
  } else {
    Write-Host "  Existing access settings were unchanged."
    Write-Host "  Registration follows the access settings already present in .env." -ForegroundColor DarkGray
  }
}
