<#
.SYNOPSIS
  Keel installer for Windows.

.DESCRIPTION
  Installs Keel into a directory, configures it, builds it, and optionally
  registers a scheduled task so it starts on boot.

  Re-running is safe: an existing install is updated and an existing .env is
  never overwritten.

.EXAMPLE
  irm https://raw.githubusercontent.com/AES256Afro/Keel/main/install.ps1 | iex

.EXAMPLE
  .\install.ps1 -Dir C:\Keel -Port 3000 -Owner you@example.com -Service
#>
[CmdletBinding()]
param(
  [string]$Dir     = "$env:LOCALAPPDATA\Keel",
  [int]   $Port    = 3000,
  [string]$Owner   = "",
  [string]$Branch  = "main",
  [string]$Repo    = "https://github.com/AES256Afro/Keel",
  [switch]$Service,
  [switch]$Yes
)

$ErrorActionPreference = "Stop"

function Say  ($m) { Write-Host "==> $m" -ForegroundColor White }
function Ok   ($m) { Write-Host "  [ok] $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  [!]  $m" -ForegroundColor Yellow }
function Die  ($m) { Write-Host "  [x]  $m" -ForegroundColor Red; exit 1 }

function Confirm-Step($message) {
  if ($Yes) { return $true }
  $reply = Read-Host "  $message [y/N]"
  return $reply -match '^[yY]'
}

Say "Keel installer"
Write-Host "  target: $Dir (port $Port)" -ForegroundColor DarkGray
Write-Host ""

# ------------------------------------------------------------------- node ---
Say "Checking Node.js"
$nodeOk = $false
if (Get-Command node -ErrorAction SilentlyContinue) {
  $major = [int](((node --version) -replace '^v','') -split '\.')[0]
  if ($major -ge 20) { $nodeOk = $true; Ok "Node.js $(node --version)" }
  else { Warn "Node.js $(node --version) is too old - Keel needs 20 or newer." }
} else {
  Warn "Node.js is not installed."
}

if (-not $nodeOk) {
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    if (Confirm-Step "Install Node.js LTS with winget?") {
      winget install --id OpenJS.NodeJS.LTS --accept-source-agreements --accept-package-agreements
      # winget updates PATH for new shells only.
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                  [System.Environment]::GetEnvironmentVariable("Path","User")
    } else { Die "Node.js 20 or newer is required." }
  } else {
    Die "Install Node.js 20+ from https://nodejs.org and re-run."
  }
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    if (Confirm-Step "Install Git with winget?") {
      winget install --id Git.Git --accept-source-agreements --accept-package-agreements
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                  [System.Environment]::GetEnvironmentVariable("Path","User")
    } else { Die "git is required." }
  } else { Die "Install Git from https://git-scm.com and re-run." }
}
Ok "git present"

# ------------------------------------------------------------------ fetch ---
Say "Fetching Keel"
if (Test-Path (Join-Path $Dir ".git")) {
  git -C $Dir fetch --depth 1 origin $Branch
  git -C $Dir checkout -q $Branch 2>$null
  git -C $Dir reset --hard "origin/$Branch"
  Ok "updated $Dir"
} else {
  if ((Test-Path $Dir) -and (Get-ChildItem $Dir -Force | Measure-Object).Count -gt 0) {
    Die "$Dir exists and is not empty."
  }
  git clone --depth 1 --branch $Branch $Repo $Dir
  Ok "cloned into $Dir"
}
Set-Location $Dir

# -------------------------------------------------------------------- env ---
Say "Configuring"
$dataDir   = Join-Path $Dir "data"
$backupDir = Join-Path $Dir "backups"
New-Item -ItemType Directory -Force -Path $dataDir, $backupDir | Out-Null

$envFile = Join-Path $Dir ".env"
if (Test-Path $envFile) {
  Ok ".env already exists - leaving it alone"
} else {
  if (-not $Owner -and -not $Yes) {
    $Owner = Read-Host "  Your email (becomes the instance owner)"
  }
  $passphrase = node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))"
  # Prisma wants forward slashes in a file: URL, even on Windows.
  $dbPath = ($dataDir -replace '\\','/') + "/keel.db"
  $stamp  = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  @"
# Generated by install.ps1 on $stamp

DATABASE_URL="file:$dbPath"
PORT=$Port

# Who runs this instance. Gates the admin portal, the sign-in allowlist and the
# tunnel - this is NOT the same as owning a workspace (every account owns one).
KEEL_OWNER_EMAIL="$Owner"

# Only these accounts may sign in, and no new sign-ups. Remove both lines to
# open the instance up.
KEEL_ALLOWED_EMAILS="$Owner"
KEEL_DISABLE_SIGNUP=1

# Passphrase for encrypted backups. Keep a copy somewhere safe - without it an
# encrypted backup cannot be restored.
KEEL_BACKUP_PASSPHRASE="$passphrase"

KEEL_BACKUP_DIR="$($backupDir -replace '\\','/')"
"@ | Set-Content -Path $envFile -Encoding UTF8

  # Restrict the file to the current user - it holds the backup passphrase.
  $acl = Get-Acl $envFile
  $acl.SetAccessRuleProtection($true, $false)
  $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "$env:USERDOMAIN\$env:USERNAME", "FullControl", "Allow")
  $acl.SetAccessRule($rule)
  Set-Acl $envFile $acl

  Ok "wrote .env (owner-only)"
  Warn "back up KEEL_BACKUP_PASSPHRASE from .env - encrypted backups need it"
}

# ---------------------------------------------------------------- install ---
Say "Installing dependencies"
npm ci --no-audit --no-fund
npx prisma generate | Out-Null
Ok "dependencies installed"

Say "Creating the database"
npm run db:deploy
Ok "database ready"

Say "Building"
npm run build
Ok "built"

# ---------------------------------------------------------------- service ---
if ($Service) {
  Say "Registering the startup task"
  $taskName = "Keel"
  $npmCmd   = (Get-Command npm).Source
  # cmd.exe wrapper: npm is a shim, and Task Scheduler will not run it directly.
  $action   = New-ScheduledTaskAction -Execute "cmd.exe" `
                -Argument "/c `"$npmCmd`" start" -WorkingDirectory $Dir
  $trigger  = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
                -DontStopIfGoingOnBatteries -StartWhenAvailable `
                -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
    -Settings $settings -Description "Keel workspace server" | Out-Null
  Start-ScheduledTask -TaskName $taskName
  Ok "scheduled task '$taskName' registered and started"
}

Write-Host ""
Say "Done."
if ($Service) {
  Write-Host "  Keel is running at http://localhost:$Port" -ForegroundColor Green
} else {
  Write-Host "  Start it with:  cd `"$Dir`"; npm start"
  Write-Host "  Then open:      http://localhost:$Port"
  Write-Host "  Re-run with -Service to start it automatically at logon." -ForegroundColor DarkGray
}
Write-Host "  Register the first account - it becomes the instance owner."
