#!/usr/bin/env bash
# Unattended VPS setup for Keel - DigitalOcean, Linode, Hetzner, Vultr,
# AWS EC2, Azure VM: anything that boots Debian or Ubuntu and runs cloud-init.
#
# Paste the #cloud-config block from docs/INSTALL.md into the provider's user
# data field, or run this directly on a fresh box as root:
#
#   KEEL_DOMAIN=notes.example.com KEEL_OWNER_EMAIL=you@example.com \
#     bash deploy/cloud-init.sh
#
# It installs Docker, fetches Keel, generates secrets, and brings up the
# production stack (app + Caddy for automatic HTTPS + Litestream if you give it
# R2 credentials). Everything restarts on reboot.
set -euo pipefail

CONF=/etc/keel.conf
# shellcheck source=/dev/null
[ -f "$CONF" ] && . "$CONF"

DOMAIN="${KEEL_DOMAIN:-}"
OWNER="${KEEL_OWNER_EMAIL:-}"
DIR="${KEEL_DIR:-/opt/keel}"
REPO="${KEEL_REPO:-https://github.com/AES256Afro/Keel}"
BRANCH="${KEEL_BRANCH:-main}"

log() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die() { printf '\033[31m[x] %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "run as root (cloud-init does)."
[ -n "$DOMAIN" ] || die "KEEL_DOMAIN is required - set it in $CONF or the environment."
[ -n "$OWNER" ]  || die "KEEL_OWNER_EMAIL is required."

export DEBIAN_FRONTEND=noninteractive

log "Installing prerequisites"
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw

log "Installing Docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc 2>/dev/null \
    || curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker

log "Firewall"
# Only HTTP (for the ACME challenge), HTTPS and SSH. The app itself is never
# exposed directly - Caddy is the only thing that talks to it.
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
ufw status | head -3

log "Fetching Keel"
if [ -d "$DIR/.git" ]; then
  git -C "$DIR" fetch origin "$BRANCH"
  git -C "$DIR" reset --hard "origin/$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO" "$DIR"
fi
cd "$DIR"

log "Configuring"
if [ -f .env.prod ]; then
  echo "  .env.prod exists - leaving it alone"
else
  PASSPHRASE="$(head -c 24 /dev/urandom | base64 | tr -d '=+/')"
  cat > .env.prod <<EOF
# Generated by deploy/cloud-init.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Every hostname Caddy should obtain a certificate for.
KEEL_DOMAINS=$DOMAIN

# Who runs this instance. Gates the admin portal, the sign-in allowlist and the
# tunnel - NOT the same as owning a workspace (every account owns one).
KEEL_OWNER_EMAIL=$OWNER

# Lock the instance to this account. These win over the in-app settings, so a
# compromised session can never widen access.
KEEL_ALLOWED_EMAILS=$OWNER
KEEL_DISABLE_SIGNUP=1

# Security keys must match the host users actually reach.
KEEL_WEBAUTHN_RP_ID=$DOMAIN
KEEL_WEBAUTHN_ORIGIN=https://$DOMAIN

# Behind Caddy, so trust X-Forwarded-For for rate limiting.
KEEL_TRUST_PROXY=1

# Encrypted scheduled backups. KEEP A COPY - without it they cannot be restored.
KEEL_BACKUP_PASSPHRASE=$PASSPHRASE

# ---- Optional: continuous off-site replication to Cloudflare R2 -------------
# Fill these in and re-run \`docker compose -f docker-compose.prod.yml up -d\`
# to stream every write off the box as it happens.
# LITESTREAM_R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com
# LITESTREAM_R2_BUCKET=
# LITESTREAM_R2_ACCESS_KEY_ID=
# LITESTREAM_R2_SECRET_ACCESS_KEY=

# ---- Optional: Google sign-in ----------------------------------------------
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF
  chmod 600 .env.prod
  echo "  wrote .env.prod (mode 600)"
fi

log "Starting Keel"
docker compose -f docker-compose.prod.yml up -d --build

log "Done"
cat <<EOF

  Keel is starting at https://$DOMAIN

  Point an A record at this machine if you haven't - Caddy needs DNS to
  resolve before Let's Encrypt will issue a certificate.

  Next:
    1. Open https://$DOMAIN and register. The first account is the instance owner.
    2. Copy KEEL_BACKUP_PASSPHRASE out of $DIR/.env.prod and store it safely.
    3. Add R2 credentials to .env.prod for off-site replication.

  Logs:    docker compose -f $DIR/docker-compose.prod.yml logs -f
  Update:  $DIR/scripts/deploy/vps-update.sh $BRANCH
EOF
