#!/usr/bin/env bash
# Unattended VPS setup for Keel - DigitalOcean, Linode, Hetzner, Vultr,
# AWS EC2, Azure VM: anything that boots Debian or Ubuntu and runs cloud-init.
#
# Paste the #cloud-config block from docs/INSTALL.md into the provider's user
# data field, or run this directly on a fresh box as root:
#
#   KEEL_DOMAIN=notes.example.com KEEL_ADMIN_EMAIL=you@example.com \
#     bash deploy/cloud-init.sh
#
# It installs Docker, fetches Keel, generates secrets, and brings up the
# production stack (app + Caddy for automatic HTTPS + Litestream if you give it
# R2 credentials). Everything restarts on reboot.
set -euo pipefail

CONF=/etc/keel.conf
# shellcheck source=/dev/null
[ -f "$CONF" ] && . "$CONF"

DOMAIN="${KEEL_DOMAIN:-}"
ADMIN_EMAIL="${KEEL_ADMIN_EMAIL:-}"
DIR="${KEEL_DIR:-/opt/keel}"
REPO="${KEEL_REPO:-https://github.com/AES256Afro/Keel}"
BRANCH="${KEEL_BRANCH:-main}"

log() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die() { printf '\033[31m[x] %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "run as root (cloud-init does)."
[ -n "$DOMAIN" ] || die "KEEL_DOMAIN is required - set it in $CONF or the environment."
[ -n "$ADMIN_EMAIL" ]  || die "KEEL_ADMIN_EMAIL is required."

export DEBIAN_FRONTEND=noninteractive

log "Installing prerequisites"
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw

log "Installing Docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc 2>/dev/null \
    || curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker

log "Firewall"
# Only HTTP (for the ACME challenge), HTTPS and SSH. The app itself is never
# exposed directly - Caddy is the only thing that talks to it.
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
ufw status | head -3

log "Fetching Keel"
if [ -d "$DIR/.git" ]; then
  git -C "$DIR" fetch origin "$BRANCH"
  git -C "$DIR" reset --hard "origin/$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO" "$DIR"
fi
cd "$DIR"

log "Configuring"
if [ -f .env.caddy ]; then
  echo "  .env.caddy exists - leaving it alone"
else
  cat > .env.caddy <<EOF
# Caddy receives only the public hostname, never application credentials.
KEEL_DOMAINS=$DOMAIN
EOF
  chmod 600 .env.caddy
  echo "  wrote .env.caddy (mode 600)"
fi

if [ -f .env.prod ]; then
  echo "  .env.prod exists - leaving it alone"
else
  PASSPHRASE="$(head -c 24 /dev/urandom | base64 | tr -d '=+/')"
  OWNER_BOOTSTRAP_TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > .env.prod <<EOF
# Generated by deploy/cloud-init.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Keep the public endpoint closed until the administrator has been created over
# a private path. An email allowlist alone does not prove ownership of a
# password-registration address, and DISABLE_SIGNUP is an unconditional stop.
KEEL_ALLOWED_EMAILS=$ADMIN_EMAIL
KEEL_DISABLE_SIGNUP=1

# Paste this write-only value into the hosted claim form after registering over
# the private SSH tunnel. Remove it and recreate Keel after the claim succeeds.
KEEL_OWNER_BOOTSTRAP_TOKEN=$OWNER_BOOTSTRAP_TOKEN

# Canonical browser origin for OAuth and WebAuthn behind Caddy. The temporary
# bootstrap Compose override replaces it with the SSH-forwarded localhost URL.
KEEL_PUBLIC_URL=https://$DOMAIN

# Security keys must match the host users actually reach.
KEEL_WEBAUTHN_RP_ID=$DOMAIN
KEEL_WEBAUTHN_ORIGIN=https://$DOMAIN

# Behind Caddy, so trust X-Forwarded-For for rate limiting.
KEEL_TRUST_PROXY=1

# Encrypted scheduled backups. KEEP A COPY - without it they cannot be restored.
KEEL_BACKUP_PASSPHRASE=$PASSPHRASE

# ---- Optional: continuous off-site replication to Cloudflare R2 -------------
# Fill these in and re-run \`docker compose -f docker-compose.prod.yml up -d\`
# to stream every write off the box as it happens.
# LITESTREAM_R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com
# LITESTREAM_R2_BUCKET=
# LITESTREAM_R2_ACCESS_KEY_ID=
# LITESTREAM_R2_SECRET_ACCESS_KEY=

# ---- Optional: Google sign-in ----------------------------------------------
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF
  chmod 600 .env.prod
  echo "  wrote .env.prod (mode 600)"
fi

log "Starting Keel"
docker compose -f docker-compose.prod.yml up -d --build

log "Done"
cat <<EOF

  Keel is starting at https://$DOMAIN

  Point an A record at this machine if you haven't - Caddy needs DNS to
  resolve before Let's Encrypt will issue a certificate.

  Next:
    1. On the server, close the public proxy and enable temporary loopback access:
         cd $DIR
         sudo docker compose -f docker-compose.prod.yml stop caddy
         sudo sed -i '/^KEEL_DISABLE_SIGNUP=/d' .env.prod
         sudo docker compose -f docker-compose.prod.yml -f docker-compose.bootstrap.yml up -d --force-recreate keel
       On your laptop, leave this tunnel running:
         ssh -L 3000:127.0.0.1:3000 <ssh-user>@<server-ip>
       Register $ADMIN_EMAIL through http://localhost:3000. Open Claim this server,
       copy the protected host bootstrap token with:
         sudo sed -n 's/^KEEL_OWNER_BOOTSTRAP_TOKEN=//p' $DIR/.env.prod
       and paste it into the write-only hosted claim field. After it succeeds:
         sudo sed -i '/^KEEL_OWNER_BOOTSTRAP_TOKEN=/d' $DIR/.env.prod
       Then restore the hard registration stop:
         printf '\nKEEL_DISABLE_SIGNUP=1\n' | sudo tee -a $DIR/.env.prod >/dev/null
         sudo docker compose -f $DIR/docker-compose.prod.yml up -d --force-recreate keel
         sudo docker compose -f $DIR/docker-compose.prod.yml start caddy
       Do not restart Caddy until the hard signup stop is restored.
    2. Copy KEEL_BACKUP_PASSPHRASE out of $DIR/.env.prod and store it safely.
    3. Add R2 credentials to .env.prod for off-site replication.

  Logs:    docker compose -f $DIR/docker-compose.prod.yml logs -f
  Update:  $DIR/scripts/deploy/vps-update.sh $BRANCH
EOF
